module.exports = {
  apps: [
    {
      name: "beacon-main-server",
      script: "index.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "logs/beacon-main-server/error.json",
      out_file: "logs/beacon-main-server/out.json",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      log_type: "json",
      max_size: "1M",
      rotate_logs: true,
      max_logs: 5,
      env_file: ".env",
      env: {
        NODE_ENV: "production",
      },
      env_development: {
        NODE_ENV: "development",
      },
    },
    {
      name: "beacon-worker",
      script: "app/workers/beaconMessage.worker.js",
      // args: "bm_in",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "logs/beacon-worker-in/error.json",
      out_file: "logs/beacon-worker-in/out.json",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      log_type: "json",
      max_size: "1M",
      rotate_logs: true,
      max_logs: 5,
      env_file: ".env",
      env: {
        NODE_ENV: "production",
      },
      env_development: {
        NODE_ENV: "development",
      },
    },
    // {
    //   name: "beacon-worker-out",
    //   script: "app/workers/generic.worker.js",
    //   args: "bm_out",
    //   instances: 1,
    //   autorestart: true,
    //   watch: false,
    //   max_memory_restart: "1G",
    //   error_file: "logs/beacon-worker-out/error.json",
    //   out_file: "logs/beacon-worker-out/out.json",
    //   log_date_format: "YYYY-MM-DD HH:mm:ss",
    //   merge_logs: true,
    //   log_type: "json",
    //   max_size: "1M",
    //   rotate_logs: true,
    //   max_logs: 5,
    // },
    {
      name: "beacon-gate-wa",
      script: "app/workers/gateways/whatsapp.gateway.worker.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "logs/beacon-worker-wa/error.log",
      out_file: "logs/beacon-worker-wa/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      max_size: "1M",
      rotate_logs: true,
      max_logs: 5,
      env_file: ".env",
      env: {
        NODE_ENV: "production",
        PM2_APP_NAME: "beacon-gate-wa",
        PM2_INSTANCE_ID: "0",
        WA_SHARED_SESSION: "true",
      },
      env_development: {
        NODE_ENV: "development",
        PM2_APP_NAME: "beacon-gate-wa",
        PM2_INSTANCE_ID: "0",
        WA_SHARED_SESSION: "true",
      },
    },
  ],
};
